"""Initial NLP service schema with event_outbox

Revision ID: 4d0dba8c7053
Revises: 
Create Date: 2025-08-03 18:08:38.550397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d0dba8c7053'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_outbox',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the outbox entry'),
    sa.Column('aggregate_id', sa.String(length=255), nullable=False, comment='ID of the aggregate this event relates to'),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False, comment="Type of aggregate (e.g., 'batch', 'file_upload')"),
    sa.Column('event_type', sa.String(length=255), nullable=False, comment="Type of the event (e.g., 'huleedu.batch.student.matching.requested.v1')"),
    sa.Column('event_data', sa.JSON(), nullable=False, comment='JSON payload containing the full event envelope including topic'),
    sa.Column('event_key', sa.String(length=255), nullable=True, comment='Optional key for Kafka partitioning'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the event was created'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the event was successfully published'),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False, comment='Number of publication attempts'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Last error message if publication failed'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_outbox_aggregate', 'event_outbox', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('ix_event_outbox_event_type', 'event_outbox', ['event_type'], unique=False)
    op.create_index('ix_event_outbox_unpublished', 'event_outbox', ['published_at', 'created_at'], unique=False, postgresql_where='published_at IS NULL')
    op.create_table('nlp_analysis_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('essay_id', sa.UUID(), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('batch_id', 'essay_id', 'analysis_type', name='uq_batch_essay_type')
    )
    op.create_index('ix_nlp_analysis_jobs_batch_id', 'nlp_analysis_jobs', ['batch_id'], unique=False)
    op.create_index('ix_nlp_analysis_jobs_status', 'nlp_analysis_jobs', ['status'], unique=False)
    op.create_table('student_match_results',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=255), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.String(length=50), nullable=False),
    sa.Column('match_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1'),
    sa.ForeignKeyConstraint(['job_id'], ['nlp_analysis_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index('ix_student_match_results_confidence', 'student_match_results', ['confidence_score'], unique=False)
    op.create_index('ix_student_match_results_job_id', 'student_match_results', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_match_results_job_id', table_name='student_match_results')
    op.drop_index('ix_student_match_results_confidence', table_name='student_match_results')
    op.drop_table('student_match_results')
    op.drop_index('ix_nlp_analysis_jobs_status', table_name='nlp_analysis_jobs')
    op.drop_index('ix_nlp_analysis_jobs_batch_id', table_name='nlp_analysis_jobs')
    op.drop_table('nlp_analysis_jobs')
    op.drop_index('ix_event_outbox_unpublished', table_name='event_outbox', postgresql_where='published_at IS NULL')
    op.drop_index('ix_event_outbox_event_type', table_name='event_outbox')
    op.drop_index('ix_event_outbox_aggregate', table_name='event_outbox')
    op.drop_table('event_outbox')
    # ### end Alembic commands ###