"""add_user_profiles_table

Revision ID: adc8538fe76d
Revises: c9ba97ebc0f1
Create Date: 2025-08-18 22:15:40.905719

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adc8538fe76d"
down_revision: Union[str, None] = "c9ba97ebc0f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("locale", sa.String(length=10), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.drop_index(
        op.f("ix_email_verification_tokens_expires"), table_name="email_verification_tokens"
    )
    op.create_index(
        op.f("ix_email_verification_tokens_expires_at"),
        "email_verification_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_outbox_aggregate_id"), "event_outbox", ["aggregate_id"], unique=False
    )
    op.drop_index(op.f("ix_password_reset_tokens_expires"), table_name="password_reset_tokens")
    op.create_index(
        op.f("ix_password_reset_tokens_expires_at"),
        "password_reset_tokens",
        ["expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_password_reset_tokens_expires_at"), table_name="password_reset_tokens")
    op.create_index(
        op.f("ix_password_reset_tokens_expires"),
        "password_reset_tokens",
        ["expires_at"],
        unique=False,
    )
    op.drop_index(op.f("ix_event_outbox_aggregate_id"), table_name="event_outbox")
    op.drop_index(
        op.f("ix_email_verification_tokens_expires_at"), table_name="email_verification_tokens"
    )
    op.create_index(
        op.f("ix_email_verification_tokens_expires"),
        "email_verification_tokens",
        ["expires_at"],
        unique=False,
    )
    op.drop_table("user_profiles")
    # ### end Alembic commands ###
