"""add_event_outbox_model_sync

Revision ID: fd6447293cdb
Revises: 20250726_0001
Create Date: 2025-07-30 20:43:46.498323

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd6447293cdb"
down_revision: Union[str, None] = "20250726_0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Handle NULL correlation_id values before making NOT NULL constraint
    # For development data, generate UUIDs for any NULL correlation_ids
    op.execute(
        "UPDATE batches SET correlation_id = gen_random_uuid()::text WHERE correlation_id IS NULL"
    )
    op.execute(
        "UPDATE phase_status_log SET correlation_id = gen_random_uuid()::text "
        "WHERE correlation_id IS NULL"
    )

    op.alter_column(
        "batches", "correlation_id", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    op.drop_table_comment(
        "event_outbox",
        existing_comment="Event outbox table for reliable event publishing to Kafka",
        schema=None,
    )
    op.alter_column(
        "phase_status_log", "correlation_id", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phase_status_log", "correlation_id", existing_type=sa.VARCHAR(length=36), nullable=True
    )
    op.create_table_comment(
        "event_outbox",
        "Event outbox table for reliable event publishing to Kafka",
        existing_comment=None,
        schema=None,
    )
    op.alter_column("batches", "correlation_id", existing_type=sa.VARCHAR(length=36), nullable=True)
    # ### end Alembic commands ###
