"""Update timeout to 24 hours for complex processing

Revision ID: c15f023f2624
Revises: 20250720_0004
Create Date: 2025-07-22 22:56:29.580803

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c15f023f2624"
down_revision: str | Sequence[str] | None = "20250720_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Update timeout_seconds default from 300 to 86400 (24 hours) for complex processing
    op.alter_column(
        "batch_essay_trackers",
        "timeout_seconds",
        existing_type=sa.INTEGER(),
        server_default=sa.text("86400"),
        nullable=False,
    )

    # Make columns NOT NULL that should be required
    op.alter_column(
        "batch_essay_trackers", "course_code", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "batch_essay_trackers", "essay_instructions", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "batch_essay_trackers", "user_id", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "batch_essay_trackers",
        "correlation_id",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "essay_processing_logs",
        "correlation_id",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )

    # Clean up unnecessary constraint changes that cause conflicts
    # Skip the constraint/index modifications that cause dependency issues
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert timeout_seconds default from 86400 back to 300 (5 minutes)
    op.alter_column(
        "batch_essay_trackers",
        "timeout_seconds",
        existing_type=sa.INTEGER(),
        server_default=sa.text("300"),
        nullable=False,
    )

    # Revert nullable constraints
    op.alter_column(
        "essay_processing_logs",
        "correlation_id",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "batch_essay_trackers",
        "correlation_id",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "batch_essay_trackers", "user_id", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "batch_essay_trackers", "essay_instructions", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "batch_essay_trackers", "course_code", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###
