"""Initial schema with clean error handling

Revision ID: af94ec26dba0
Revises:
Create Date: 2025-07-10 11:18:20.892342

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af94ec26dba0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cj_batch_uploads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bos_batch_id", sa.String(length=36), nullable=False),
        sa.Column("event_correlation_id", sa.String(length=36), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("course_code", sa.String(length=50), nullable=False),
        sa.Column("essay_instructions", sa.Text(), nullable=False),
        sa.Column("expected_essay_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "FETCHING_CONTENT",
                "PERFORMING_COMPARISONS",
                "COMPLETE_STABLE",
                "COMPLETE_MAX_COMPARISONS",
                "ERROR_PROCESSING",
                "ERROR_ESSAY_PROCESSING",
                name="cj_batch_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(NOW())"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(NOW())"), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("processing_metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cj_batch_uploads_bos_batch_id"), "cj_batch_uploads", ["bos_batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_cj_batch_uploads_status"), "cj_batch_uploads", ["status"], unique=False
    )
    op.create_table(
        "cj_processed_essays",
        sa.Column("els_essay_id", sa.String(length=36), nullable=False),
        sa.Column("cj_batch_id", sa.Integer(), nullable=False),
        sa.Column("text_storage_id", sa.String(length=256), nullable=False),
        sa.Column("assessment_input_text", sa.Text(), nullable=False),
        sa.Column("current_bt_score", sa.Float(), nullable=True),
        sa.Column("comparison_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(NOW())"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(NOW())"), nullable=False),
        sa.Column("processing_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["cj_batch_id"], ["cj_batch_uploads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("els_essay_id"),
    )
    op.create_index(
        op.f("ix_cj_processed_essays_cj_batch_id"),
        "cj_processed_essays",
        ["cj_batch_id"],
        unique=False,
    )
    op.create_table(
        "cj_comparison_pairs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cj_batch_id", sa.Integer(), nullable=False),
        sa.Column("essay_a_els_id", sa.String(length=36), nullable=False),
        sa.Column("essay_b_els_id", sa.String(length=36), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("winner", sa.String(length=20), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.Column("raw_llm_response", sa.Text(), nullable=True),
        sa.Column(
            "error_code",
            sa.Enum(
                "UNKNOWN_ERROR",
                "VALIDATION_ERROR",
                "RESOURCE_NOT_FOUND",
                "CONFIGURATION_ERROR",
                "EXTERNAL_SERVICE_ERROR",
                "KAFKA_PUBLISH_ERROR",
                "CONTENT_SERVICE_ERROR",
                "SPELLCHECK_SERVICE_ERROR",
                "NLP_SERVICE_ERROR",
                "AI_FEEDBACK_SERVICE_ERROR",
                "CJ_ASSESSMENT_SERVICE_ERROR",
                "MISSING_REQUIRED_FIELD",
                "INVALID_CONFIGURATION",
                "TIMEOUT",
                "CONNECTION_ERROR",
                "SERVICE_UNAVAILABLE",
                "RATE_LIMIT",
                "QUOTA_EXCEEDED",
                "AUTHENTICATION_ERROR",
                "INVALID_API_KEY",
                "INVALID_REQUEST",
                "INVALID_RESPONSE",
                "PARSING_ERROR",
                "CIRCUIT_BREAKER_OPEN",
                "REQUEST_QUEUED",
                "PROCESSING_ERROR",
                "INITIALIZATION_FAILED",
                name="errorcode",
            ),
            nullable=True,
        ),
        sa.Column("error_correlation_id", sa.UUID(), nullable=True),
        sa.Column("error_timestamp", sa.DateTime(), nullable=True),
        sa.Column("error_service", sa.String(length=100), nullable=True),
        sa.Column("error_details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(NOW())"), nullable=False),
        sa.Column("processing_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["cj_batch_id"], ["cj_batch_uploads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["essay_a_els_id"],
            ["cj_processed_essays.els_essay_id"],
        ),
        sa.ForeignKeyConstraint(
            ["essay_b_els_id"],
            ["cj_processed_essays.els_essay_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cj_comparison_pairs_cj_batch_id"),
        "cj_comparison_pairs",
        ["cj_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cj_comparison_pairs_essay_a_els_id"),
        "cj_comparison_pairs",
        ["essay_a_els_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cj_comparison_pairs_essay_b_els_id"),
        "cj_comparison_pairs",
        ["essay_b_els_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cj_comparison_pairs_essay_b_els_id"), table_name="cj_comparison_pairs")
    op.drop_index(op.f("ix_cj_comparison_pairs_essay_a_els_id"), table_name="cj_comparison_pairs")
    op.drop_index(op.f("ix_cj_comparison_pairs_cj_batch_id"), table_name="cj_comparison_pairs")
    op.drop_table("cj_comparison_pairs")
    op.drop_index(op.f("ix_cj_processed_essays_cj_batch_id"), table_name="cj_processed_essays")
    op.drop_table("cj_processed_essays")
    op.drop_index(op.f("ix_cj_batch_uploads_status"), table_name="cj_batch_uploads")
    op.drop_index(op.f("ix_cj_batch_uploads_bos_batch_id"), table_name="cj_batch_uploads")
    op.drop_table("cj_batch_uploads")
    # ### end Alembic commands ###
