"""Add judge_rubric_storage_id to assessment_instructions

Revision ID: 4aefc9fed780
Revises: 52a8b9c3e4f1
Create Date: 2025-11-12 19:48:52.497334

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4aefc9fed780"
down_revision: Union[str, Sequence[str], None] = "52a8b9c3e4f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "anchor_essay_references",
        "grade",
        existing_type=sa.VARCHAR(length=4),
        comment=None,
        existing_comment="Swedish grade (e.g., A, A-, B, B-, C+, C, C-, D+, D, D-, E, E-, F)",
        existing_nullable=False,
    )
    op.alter_column(
        "anchor_essay_references",
        "grade_scale",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment=(  # noqa: E501
            "Grade scale identifier (swedish_8_anchor, eng5_np_legacy_9_step, "
            "eng5_np_national_9_step)"
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'swedish_8_anchor'::character varying"),
    )
    op.drop_table_comment(
        "anchor_essay_references",
        existing_comment="References to pre-graded anchor essays stored in Content Service",
        schema=None,
    )
    op.add_column(
        "assessment_instructions",
        sa.Column("judge_rubric_storage_id", sa.String(length=255), nullable=True),
    )
    op.alter_column(
        "assessment_instructions",
        "grade_scale",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Grade scale identifier associated with the assignment",
        existing_nullable=False,
        existing_server_default=sa.text("'swedish_8_anchor'::character varying"),
    )
    op.drop_constraint(
        op.f("assessment_instructions_assignment_id_key"), "assessment_instructions", type_="unique"
    )
    op.drop_index(
        op.f("ix_assessment_instructions_assignment_id"), table_name="assessment_instructions"
    )
    op.create_index(
        op.f("ix_assessment_instructions_assignment_id"),
        "assessment_instructions",
        ["assignment_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_assessment_instructions_judge_rubric_storage_id"),
        "assessment_instructions",
        ["judge_rubric_storage_id"],
        unique=False,
    )
    op.drop_table_comment(
        "assessment_instructions",
        existing_comment=(
            "Stores assessment instructions for AI judges, linked to assignment or course"
        ),
        schema=None,
    )
    op.alter_column(
        "cj_batch_uploads",
        "assignment_id",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Optional assignment context for grade projection",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("idx_cj_processed_essays_anchor"),
        table_name="cj_processed_essays",
        postgresql_where="(is_anchor = true)",
    )
    op.alter_column(
        "event_outbox",
        "id",
        existing_type=sa.UUID(),
        comment="Unique identifier for the outbox entry",
        existing_nullable=False,
        existing_server_default=sa.text("gen_random_uuid()"),
    )
    op.alter_column(
        "event_outbox",
        "aggregate_id",
        existing_type=sa.VARCHAR(length=255),
        comment="ID of the aggregate (batch_id, cj_batch_id) that generated this event",
        existing_nullable=False,
    )
    op.alter_column(
        "event_outbox",
        "aggregate_type",
        existing_type=sa.VARCHAR(length=100),
        comment="Type of aggregate (cj_batch, grade_projection) for categorization",
        existing_nullable=False,
    )
    op.alter_column(
        "event_outbox",
        "event_type",
        existing_type=sa.VARCHAR(length=255),
        comment="Type/topic of the event (e.g., cj.assessment.completed.v1)",
        existing_nullable=False,
    )
    op.alter_column(
        "event_outbox",
        "event_data",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="The complete event data as JSON (EventEnvelope)",
        existing_nullable=False,
    )
    op.alter_column(
        "event_outbox",
        "event_key",
        existing_type=sa.VARCHAR(length=255),
        comment="Kafka message key for partitioning",
        existing_nullable=True,
    )
    op.alter_column(
        "event_outbox",
        "topic",
        existing_type=sa.VARCHAR(length=255),
        comment="Kafka topic to publish to",
        existing_nullable=False,
    )
    op.alter_column(
        "event_outbox",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the event was created",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "event_outbox",
        "published_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the event was successfully published to Kafka",
        existing_nullable=True,
    )
    op.alter_column(
        "event_outbox",
        "retry_count",
        existing_type=sa.INTEGER(),
        comment="Number of publish attempts",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "event_outbox",
        "last_error",
        existing_type=sa.TEXT(),
        comment="Last error message if publishing failed",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_event_outbox_aggregate"), table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_event_type"), table_name="event_outbox")
    op.drop_index(
        op.f("ix_event_outbox_unpublished"),
        table_name="event_outbox",
        postgresql_where="(published_at IS NULL)",
    )
    op.create_index(
        op.f("ix_event_outbox_aggregate_id"), "event_outbox", ["aggregate_id"], unique=False
    )
    op.alter_column(
        "grade_projections",
        "primary_grade",
        existing_type=sa.VARCHAR(length=4),
        comment=None,
        existing_comment="Swedish primary grade assigned to the essay",
        existing_nullable=False,
    )
    op.alter_column(
        "grade_projections",
        "grade_scale",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Grade scale used for this projection",
        existing_nullable=False,
        existing_server_default=sa.text("'swedish_8_anchor'::character varying"),
    )
    op.alter_column(
        "grade_projections",
        "population_prior",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Population-based prior probability for this grade",
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("grade_projections_cj_batch_id_fkey"), "grade_projections", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("grade_projections_els_essay_id_fkey"), "grade_projections", type_="foreignkey"
    )
    op.create_foreign_key(None, "grade_projections", "cj_batch_uploads", ["cj_batch_id"], ["id"])
    op.create_foreign_key(
        None, "grade_projections", "cj_processed_essays", ["els_essay_id"], ["els_essay_id"]
    )
    op.drop_table_comment(
        "grade_projections",
        existing_comment="Stores grade projections with confidence scores for assessed essays",
        schema=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "grade_projections",
        "Stores grade projections with confidence scores for assessed essays",
        existing_comment=None,
        schema=None,
    )
    op.drop_constraint(None, "grade_projections", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "grade_projections", type_="foreignkey")  # type: ignore[arg-type]
    op.create_foreign_key(
        op.f("grade_projections_els_essay_id_fkey"),
        "grade_projections",
        "cj_processed_essays",
        ["els_essay_id"],
        ["els_essay_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("grade_projections_cj_batch_id_fkey"),
        "grade_projections",
        "cj_batch_uploads",
        ["cj_batch_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "grade_projections",
        "population_prior",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Population-based prior probability for this grade",
        existing_nullable=True,
    )
    op.alter_column(
        "grade_projections",
        "grade_scale",
        existing_type=sa.VARCHAR(length=50),
        comment="Grade scale used for this projection",
        existing_nullable=False,
        existing_server_default=sa.text("'swedish_8_anchor'::character varying"),
    )
    op.alter_column(
        "grade_projections",
        "primary_grade",
        existing_type=sa.VARCHAR(length=4),
        comment="Swedish primary grade assigned to the essay",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_event_outbox_aggregate_id"), table_name="event_outbox")
    op.create_index(
        op.f("ix_event_outbox_unpublished"),
        "event_outbox",
        ["published_at", "created_at"],
        unique=False,
        postgresql_where="(published_at IS NULL)",
    )
    op.create_index(
        op.f("ix_event_outbox_event_type"), "event_outbox", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_event_outbox_aggregate"),
        "event_outbox",
        ["aggregate_type", "aggregate_id"],
        unique=False,
    )
    op.alter_column(
        "event_outbox",
        "last_error",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Last error message if publishing failed",
        existing_nullable=True,
    )
    op.alter_column(
        "event_outbox",
        "retry_count",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Number of publish attempts",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "event_outbox",
        "published_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When the event was successfully published to Kafka",
        existing_nullable=True,
    )
    op.alter_column(
        "event_outbox",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When the event was created",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "event_outbox",
        "topic",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Kafka topic to publish to",
        existing_nullable=False,
    )
    op.alter_column(
        "event_outbox",
        "event_key",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Kafka message key for partitioning",
        existing_nullable=True,
    )
    op.alter_column(
        "event_outbox",
        "event_data",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment="The complete event data as JSON (EventEnvelope)",
        existing_nullable=False,
    )
    op.alter_column(
        "event_outbox",
        "event_type",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Type/topic of the event (e.g., cj.assessment.completed.v1)",
        existing_nullable=False,
    )
    op.alter_column(
        "event_outbox",
        "aggregate_type",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Type of aggregate (cj_batch, grade_projection) for categorization",
        existing_nullable=False,
    )
    op.alter_column(
        "event_outbox",
        "aggregate_id",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="ID of the aggregate (batch_id, cj_batch_id) that generated this event",
        existing_nullable=False,
    )
    op.alter_column(
        "event_outbox",
        "id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Unique identifier for the outbox entry",
        existing_nullable=False,
        existing_server_default=sa.text("gen_random_uuid()"),
    )
    op.create_index(
        op.f("idx_cj_processed_essays_anchor"),
        "cj_processed_essays",
        ["is_anchor"],
        unique=False,
        postgresql_where="(is_anchor = true)",
    )
    op.alter_column(
        "cj_batch_uploads",
        "assignment_id",
        existing_type=sa.VARCHAR(length=100),
        comment="Optional assignment context for grade projection",
        existing_nullable=True,
    )
    op.create_table_comment(
        "assessment_instructions",
        "Stores assessment instructions for AI judges, linked to assignment or course",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(
        op.f("ix_assessment_instructions_judge_rubric_storage_id"),
        table_name="assessment_instructions",
    )
    op.drop_index(
        op.f("ix_assessment_instructions_assignment_id"), table_name="assessment_instructions"
    )
    op.create_index(
        op.f("ix_assessment_instructions_assignment_id"),
        "assessment_instructions",
        ["assignment_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("assessment_instructions_assignment_id_key"),
        "assessment_instructions",
        ["assignment_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "assessment_instructions",
        "grade_scale",
        existing_type=sa.VARCHAR(length=50),
        comment="Grade scale identifier associated with the assignment",
        existing_nullable=False,
        existing_server_default=sa.text("'swedish_8_anchor'::character varying"),
    )
    op.drop_column("assessment_instructions", "judge_rubric_storage_id")
    op.create_table_comment(
        "anchor_essay_references",
        "References to pre-graded anchor essays stored in Content Service",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "anchor_essay_references",
        "grade_scale",
        existing_type=sa.VARCHAR(length=50),
        comment=(
            "Grade scale identifier (swedish_8_anchor, eng5_np_legacy_9_step, "
            "eng5_np_national_9_step)"
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'swedish_8_anchor'::character varying"),
    )
    op.alter_column(
        "anchor_essay_references",
        "grade",
        existing_type=sa.VARCHAR(length=4),
        comment="Swedish grade (e.g., A, A-, B, B-, C+, C, C-, D+, D, D-, E, E-, F)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
