"""fix_error_timestamp_timezone_support

Revision ID: d03b409524ae
Revises: d3f4e5f6a7b8
Create Date: 2025-07-17 01:31:11.667825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d03b409524ae"
down_revision: Union[str, Sequence[str], None] = "d3f4e5f6a7b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cj_comparison_pairs", sa.Column("request_correlation_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "cj_comparison_pairs", sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "cj_comparison_pairs", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column(
        "cj_comparison_pairs",
        "error_timestamp",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_cj_comparison_pairs_request_correlation_id"),
        "cj_comparison_pairs",
        ["request_correlation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cj_comparison_pairs_request_correlation_id"), table_name="cj_comparison_pairs"
    )
    op.alter_column(
        "cj_comparison_pairs",
        "error_timestamp",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_column("cj_comparison_pairs", "completed_at")
    op.drop_column("cj_comparison_pairs", "submitted_at")
    op.drop_column("cj_comparison_pairs", "request_correlation_id")
    # ### end Alembic commands ###
