"""Add user_id and org_id fields to CJBatchUpload for credit attribution

Revision ID: baf9cf9c8c5c
Revises: swedish_8_grade_system
Create Date: 2025-08-31 00:07:25.942232

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "baf9cf9c8c5c"
down_revision: Union[str, Sequence[str], None] = "swedish_8_grade_system"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cj_batch_uploads", sa.Column("user_id", sa.String(length=255), nullable=True))
    op.add_column("cj_batch_uploads", sa.Column("org_id", sa.String(length=255), nullable=True))
    op.create_index(
        op.f("ix_cj_batch_uploads_org_id"), "cj_batch_uploads", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_cj_batch_uploads_user_id"), "cj_batch_uploads", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cj_batch_uploads_user_id"), table_name="cj_batch_uploads")
    op.drop_index(op.f("ix_cj_batch_uploads_org_id"), table_name="cj_batch_uploads")
    op.drop_column("cj_batch_uploads", "org_id")
    op.drop_column("cj_batch_uploads", "user_id")
    # ### end Alembic commands ###
