from __future__ import annotations

from typing import Optional, Protocol


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, hash: str, password: str) -> bool: ...


class TokenIssuer(Protocol):
    def issue_access_token(self, user_id: str, org_id: str | None, roles: list[str]) -> str: ...
    def issue_refresh_token(self, user_id: str) -> tuple[str, str]: ...  # token, jti
    def verify(self, token: str) -> dict: ...


class UserRepo(Protocol):
    async def create_user(self, email: str, org_id: str | None, password_hash: str) -> dict: ...
    async def get_user_by_email(self, email: str) -> Optional[dict]: ...
    async def set_email_verified(self, user_id: str) -> None: ...


class SessionRepo(Protocol):
    async def store_refresh(self, user_id: str, jti: str, exp_ts: int) -> None: ...
    async def revoke_refresh(self, jti: str) -> None: ...
    async def is_refresh_valid(self, jti: str) -> bool: ...


class IdentityEventPublisherProtocol(Protocol):
    async def publish_user_registered(self, user: dict, correlation_id: str) -> None: ...

