from __future__ import annotations

from datetime import datetime
from typing import Optional, Protocol


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, hash: str, password: str) -> bool: ...


class TokenIssuer(Protocol):
    def issue_access_token(self, user_id: str, org_id: str | None, roles: list[str]) -> str: ...
    def issue_refresh_token(self, user_id: str) -> tuple[str, str]: ...  # token, jti
    def verify(self, token: str) -> dict: ...


class UserRepo(Protocol):
    async def create_user(self, email: str, org_id: str | None, password_hash: str) -> dict: ...
    async def get_user_by_email(self, email: str) -> Optional[dict]: ...
    async def set_email_verified(self, user_id: str) -> None: ...
    async def create_email_verification_token(
        self, user_id: str, token: str, expires_at: datetime
    ) -> dict: ...
    async def get_email_verification_token(self, token: str) -> Optional[dict]: ...
    async def mark_token_used(self, token_id: str) -> None: ...
    async def invalidate_user_tokens(self, user_id: str) -> None: ...
    async def create_password_reset_token(
        self, user_id: str, token: str, expires_at: datetime
    ) -> dict: ...
    async def get_password_reset_token(self, token: str) -> Optional[dict]: ...
    async def mark_reset_token_used(self, token_id: str) -> None: ...
    async def invalidate_password_reset_tokens(self, user_id: str) -> None: ...
    async def update_user_password(self, user_id: str, password_hash: str) -> None: ...


class SessionRepo(Protocol):
    async def store_refresh(self, user_id: str, jti: str, exp_ts: int) -> None: ...
    async def revoke_refresh(self, jti: str) -> None: ...
    async def is_refresh_valid(self, jti: str) -> bool: ...


class IdentityEventPublisherProtocol(Protocol):
    async def publish_user_registered(self, user: dict, correlation_id: str) -> None: ...

    async def publish_login_succeeded(self, user: dict, correlation_id: str) -> None: ...

    async def publish_login_failed(
        self, email: str, failure_reason: str, correlation_id: str
    ) -> None: ...

    async def publish_email_verification_requested(
        self, user: dict, token_id: str, expires_at: datetime, correlation_id: str
    ) -> None: ...

    async def publish_email_verified(self, user: dict, correlation_id: str) -> None: ...

    async def publish_password_reset_requested(
        self, user: dict, token_id: str, expires_at: datetime, correlation_id: str
    ) -> None: ...

    async def publish_password_reset_completed(self, user: dict, correlation_id: str) -> None: ...
