"""Add missing outbox columns for shared OutboxManager

Revision ID: a7754a58c81a
Revises: 0e4fab81921a
Create Date: 2025-08-29 09:29:26.586463

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7754a58c81a"
down_revision: Union[str, Sequence[str], None] = "0e4fab81921a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing columns for shared OutboxManager compatibility
    op.add_column("event_outbox", sa.Column("event_key", sa.String(255), nullable=True))
    op.add_column(
        "event_outbox", sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column("event_outbox", sa.Column("last_error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove columns added for shared OutboxManager compatibility
    op.drop_column("event_outbox", "last_error")
    op.drop_column("event_outbox", "retry_count")
    op.drop_column("event_outbox", "event_key")
    # ### end Alembic commands ###
