"""Initial entitlements schema

Revision ID: 0e4fab81921a
Revises:
Create Date: 2025-08-24 17:39:12.906177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e4fab81921a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_balances",
        sa.Column("subject_type", sa.Enum("user", "org", name="subject_type_enum"), nullable=False),
        sa.Column("subject_id", sa.String(length=255), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("subject_type", "subject_id"),
    )
    op.create_index(
        op.f("ix_credit_balances_balance"), "credit_balances", ["balance"], unique=False
    )
    op.create_index(
        op.f("ix_credit_balances_created_at"), "credit_balances", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_credit_balances_subject_id"), "credit_balances", ["subject_id"], unique=False
    )
    op.create_index("ix_credit_balances_updated", "credit_balances", ["updated_at"], unique=False)
    op.create_table(
        "credit_operations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "subject_type",
            sa.Enum("USER", "ORG", name="credit_op_subject_type_enum"),
            nullable=False,
        ),
        sa.Column("subject_id", sa.String(length=255), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.String(length=255), nullable=True),
        sa.Column(
            "consumed_from",
            sa.Enum("USER", "ORG", name="credit_op_consumed_from_enum"),
            nullable=False,
        ),
        sa.Column("correlation_id", sa.String(length=255), nullable=False),
        sa.Column(
            "operation_status",
            sa.Enum("pending", "completed", "failed", name="operation_status_enum"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_credit_operations_batch_id"), "credit_operations", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_credit_operations_consumed_from"),
        "credit_operations",
        ["consumed_from"],
        unique=False,
    )
    op.create_index(
        "ix_credit_operations_correlation", "credit_operations", ["correlation_id"], unique=False
    )
    op.create_index(
        op.f("ix_credit_operations_correlation_id"),
        "credit_operations",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credit_operations_created_at"), "credit_operations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_credit_operations_metric"), "credit_operations", ["metric"], unique=False
    )
    op.create_index(
        "ix_credit_operations_metric_created",
        "credit_operations",
        ["metric", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credit_operations_operation_status"),
        "credit_operations",
        ["operation_status"],
        unique=False,
    )
    op.create_index(
        "ix_credit_operations_status_created",
        "credit_operations",
        ["operation_status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_credit_operations_subject",
        "credit_operations",
        ["subject_type", "subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credit_operations_subject_id"), "credit_operations", ["subject_id"], unique=False
    )
    op.create_index(
        op.f("ix_credit_operations_subject_type"),
        "credit_operations",
        ["subject_type"],
        unique=False,
    )
    op.create_table(
        "event_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=200), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=False),
        sa.Column("topic", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_outbox_aggregate_id"), "event_outbox", ["aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_outbox_aggregate_type"), "event_outbox", ["aggregate_type"], unique=False
    )
    op.create_index(
        op.f("ix_event_outbox_created_at"), "event_outbox", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_event_outbox_event_type"), "event_outbox", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_event_outbox_topic"), "event_outbox", ["topic"], unique=False)
    op.create_index(
        "ix_outbox_aggregate", "event_outbox", ["aggregate_type", "aggregate_id"], unique=False
    )
    op.create_index(
        "ix_outbox_cleanup", "event_outbox", ["published_at", "created_at"], unique=False
    )
    op.create_index(
        "ix_outbox_unpublished",
        "event_outbox",
        ["published_at", "topic", "created_at"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "rate_limit_buckets",
        sa.Column("subject_id", sa.String(length=255), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("subject_id", "metric", "window_start"),
    )
    op.create_index(
        "ix_rate_limit_cleanup", "rate_limit_buckets", ["window_start", "metric"], unique=False
    )
    op.create_index(
        "ix_rate_limit_subject_metric", "rate_limit_buckets", ["subject_id", "metric"], unique=False
    )
    op.create_index("ix_rate_limit_window", "rate_limit_buckets", ["window_start"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rate_limit_window", table_name="rate_limit_buckets")
    op.drop_index("ix_rate_limit_subject_metric", table_name="rate_limit_buckets")
    op.drop_index("ix_rate_limit_cleanup", table_name="rate_limit_buckets")
    op.drop_table("rate_limit_buckets")
    op.drop_index(
        "ix_outbox_unpublished",
        table_name="event_outbox",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_index("ix_outbox_cleanup", table_name="event_outbox")
    op.drop_index("ix_outbox_aggregate", table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_topic"), table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_event_type"), table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_created_at"), table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_aggregate_type"), table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_aggregate_id"), table_name="event_outbox")
    op.drop_table("event_outbox")
    op.drop_index(op.f("ix_credit_operations_subject_type"), table_name="credit_operations")
    op.drop_index(op.f("ix_credit_operations_subject_id"), table_name="credit_operations")
    op.drop_index("ix_credit_operations_subject", table_name="credit_operations")
    op.drop_index("ix_credit_operations_status_created", table_name="credit_operations")
    op.drop_index(op.f("ix_credit_operations_operation_status"), table_name="credit_operations")
    op.drop_index("ix_credit_operations_metric_created", table_name="credit_operations")
    op.drop_index(op.f("ix_credit_operations_metric"), table_name="credit_operations")
    op.drop_index(op.f("ix_credit_operations_created_at"), table_name="credit_operations")
    op.drop_index(op.f("ix_credit_operations_correlation_id"), table_name="credit_operations")
    op.drop_index("ix_credit_operations_correlation", table_name="credit_operations")
    op.drop_index(op.f("ix_credit_operations_consumed_from"), table_name="credit_operations")
    op.drop_index(op.f("ix_credit_operations_batch_id"), table_name="credit_operations")
    op.drop_table("credit_operations")
    op.drop_index("ix_credit_balances_updated", table_name="credit_balances")
    op.drop_index(op.f("ix_credit_balances_subject_id"), table_name="credit_balances")
    op.drop_index(op.f("ix_credit_balances_created_at"), table_name="credit_balances")
    op.drop_index(op.f("ix_credit_balances_balance"), table_name="credit_balances")
    op.drop_table("credit_balances")
    # ### end Alembic commands ###
