"""
Pydantic models for AI feedback processing events.

These models define the data structures for AI feedback processing inputs
and results as specified in the PRD.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field

from ..domain_enums import CourseCode
from ..event_enums import ProcessingEvent
from ..metadata_models import StorageReferenceMetadata
from .base_event_models import ProcessingUpdate

__all__ = [
    "AIFeedbackInputDataV1",
    "AIFeedbackResultDataV1",
]


class AIFeedbackMetadata(BaseModel):
    """Metadata about AI feedback generation and processing."""

    model_version: str
    generation_timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
    feedback_type: str  # e.g., "student_facing", "detailed_analysis", "editor_revision"
    processing_time_seconds: float | None = None


class AIFeedbackInputDataV1(BaseModel):
    """Input data structure needed for AI feedback processing requests."""

    text_storage_id: str
    course_code: CourseCode
    student_prompt_ref: StorageReferenceMetadata | None = Field(
        default=None,
        description="Content Service reference for the student-facing prompt text",
    )
    language: str
    class_designation: str | None = None
    user_id_of_batch_owner: str | None = None


class AIFeedbackResultDataV1(ProcessingUpdate):
    """
    Data payload for an event indicating the result of AI feedback processing for an essay.
    This event is published by the AI Feedback Service and consumed by ELS.
    It follows the "thin event" principle by referencing bulky feedback content
    stored elsewhere if applicable.
    """

    # Inherits entity_ref, timestamp from BaseEventData
    # Inherits status (EssayStatus), system_metadata from ProcessingUpdate

    event_name: ProcessingEvent = Field(
        default=ProcessingEvent.ESSAY_AIFEEDBACK_COMPLETED,
        description="The specific type of processing event.",
    )
    # The 'status' field (inherited from ProcessingUpdate) will be populated with
    # EssayStatus.AI_FEEDBACK_COMPLETED_SUCCESS or EssayStatus.AI_FEEDBACK_FAILED.

    # Contains contextual information about the feedback request and generation,
    # flags indicating what was generated, model versions, etc.
    # This itself is a Pydantic model.
    feedback_details: AIFeedbackMetadata = Field(
        description="Metadata and summary details about the generated AI feedback.",
    )

    # Optional: If the actual generated feedback text (e.g., student-facing report,
    # editor revision suggestions) is substantial and stored in the Content Service,
    # this field will hold the storage_id.
    # If feedback is small enough or always part of AIFeedbackMetadata, this might be omitted.
    feedback_content_storage_id: str | None = Field(
        default=None,
        description="Optional storage ID of the detailed feedback content if stored separately.",
    )

    # Optional: Any specific metrics or scores generated by the AI Feedback service
    # that are not part of AIFeedbackMetadata.
    additional_metrics: dict[str, Any] | None = Field(
        default=None,
        description=(
            "Optional dictionary for any additional metrics or scores from feedback processing."
        ),
    )

    # The system_metadata (inherited from ProcessingUpdate) should be populated by the
    # AI Feedback Service to reflect the outcome of its processing attempt:
    # system_metadata.processing_stage would be ProcessingStage.COMPLETED or ProcessingStage.FAILED.
    # system_metadata.error_info would contain details if the processing_stage is FAILED.
