"""Initial email service schema

Revision ID: ce41648d3fde
Revises:
Create Date: 2025-08-23 15:28:03.086629

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ce41648d3fde"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
