"""Replace email_outbox_events with standard event_outbox table

Revision ID: 32be4d7e70d0
Revises: ce41648d3fde
Create Date: 2025-08-23 15:45:32.576749

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "32be4d7e70d0"
down_revision: Union[str, Sequence[str], None] = "ce41648d3fde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("aggregate_id", sa.String(length=255), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=False),
        sa.Column("event_key", sa.String(length=255), nullable=True),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_event_outbox_aggregate",
        "event_outbox",
        ["aggregate_type", "aggregate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_outbox_aggregate_id"), "event_outbox", ["aggregate_id"], unique=False
    )
    op.create_index("ix_event_outbox_event_type", "event_outbox", ["event_type"], unique=False)
    op.create_index("ix_event_outbox_topic", "event_outbox", ["topic"], unique=False)
    op.create_index(
        "ix_event_outbox_unpublished_topic",
        "event_outbox",
        ["published_at", "topic", "created_at"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_index(op.f("ix_email_outbox_correlation"), table_name="email_outbox_events")
    op.drop_index(op.f("ix_email_outbox_events_topic"), table_name="email_outbox_events")
    op.drop_index(op.f("ix_email_outbox_unpublished_priority"), table_name="email_outbox_events")
    op.drop_table("email_outbox_events")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_outbox_events",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("topic", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("event_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("source_service", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("correlation_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "event_data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("published_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("email_outbox_events_pkey")),
    )
    op.create_index(
        op.f("ix_email_outbox_unpublished_priority"),
        "email_outbox_events",
        ["published_at", "topic", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_outbox_events_topic"), "email_outbox_events", ["topic"], unique=False
    )
    op.create_index(
        op.f("ix_email_outbox_correlation"), "email_outbox_events", ["correlation_id"], unique=False
    )
    op.drop_index(
        "ix_event_outbox_unpublished_topic",
        table_name="event_outbox",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_index("ix_event_outbox_topic", table_name="event_outbox")
    op.drop_index("ix_event_outbox_event_type", table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_aggregate_id"), table_name="event_outbox")
    op.drop_index("ix_event_outbox_aggregate", table_name="event_outbox")
    op.drop_table("event_outbox")
    # ### end Alembic commands ###
