"""Add batch_id to essay_student_associations

Revision ID: 7d21f7fdd41e
Revises: 220aebb1348a
Create Date: 2025-08-04 00:17:37.037383

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d21f7fdd41e"
down_revision: Union[str, Sequence[str], None] = "220aebb1348a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("essay_student_associations", sa.Column("batch_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_essay_student_associations_batch_id"),
        "essay_student_associations",
        ["batch_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_essay_student_associations_batch_id"), table_name="essay_student_associations"
    )
    op.drop_column("essay_student_associations", "batch_id")
    # ### end Alembic commands ###
