"""Initial schema with phase_completions table

Revision ID: 5e6efbbdb321
Revises:
Create Date: 2025-08-15 21:05:21.048697

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5e6efbbdb321"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phase_completions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("batch_id", sa.String(length=255), nullable=False),
        sa.Column("phase_name", sa.String(length=100), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("phase_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "phase_name", name="uq_batch_phase"),
    )
    op.create_index("idx_phase_completions_batch", "phase_completions", ["batch_id"], unique=False)
    op.create_index(
        "idx_phase_completions_batch_completed",
        "phase_completions",
        ["batch_id", "completed"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_phase_completions_batch_completed", table_name="phase_completions")
    op.drop_index("idx_phase_completions_batch", table_name="phase_completions")
    op.drop_table("phase_completions")
    # ### end Alembic commands ###
