"""Service-specific error handling for LLM Provider Service."""

from huleedu_service_libs.error_handling import (
    HuleEduError,
    raise_authentication_error,
    raise_circuit_breaker_open,
    raise_configuration_error,
    raise_connection_error,
    raise_external_service_error,
    raise_invalid_api_key,
    raise_invalid_request,
    raise_invalid_response,
    raise_llm_model_not_found,
    raise_llm_provider_error,
    raise_llm_provider_service_error,
    raise_llm_queue_full_error,
    raise_llm_response_validation_error,
    raise_parsing_error,
    raise_processing_error,
    raise_quota_exceeded,
    raise_rate_limit_error,
    raise_resource_not_found,
    raise_service_unavailable,
    raise_timeout_error,
    raise_validation_error,
)

__all__ = [
    "HuleEduError",
    "raise_llm_provider_service_error",
    "raise_llm_provider_error",
    "raise_llm_model_not_found",
    "raise_llm_response_validation_error",
    "raise_llm_queue_full_error",
    "raise_authentication_error",
    "raise_circuit_breaker_open",
    "raise_configuration_error",
    "raise_connection_error",
    "raise_external_service_error",
    "raise_invalid_api_key",
    "raise_invalid_request",
    "raise_invalid_response",
    "raise_parsing_error",
    "raise_processing_error",
    "raise_quota_exceeded",
    "raise_rate_limit_error",
    "raise_resource_not_found",
    "raise_service_unavailable",
    "raise_timeout_error",
    "raise_validation_error",
]
